package com.guildworkman.api.payment.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.Instant;

/**
 * An inbound charge: one client paying for one engagement.
 *
 * <p>This is <b>derived state</b>, not the source of truth. The authoritative
 * record of what money moved is the append-only
 * {@link LedgerTransaction}/{@link LedgerEntry} pair; this row exists so the
 * API can answer "what is the status of reference X?" without replaying the
 * journal, and so the state machine has somewhere to live. Everything here
 * can be rebuilt from the ledger plus the processed-event log — which is why
 * it is safe for it to be mutable while the ledger is not.
 *
 * <p>{@code reference} is Paystack's transaction reference, generated by this
 * service at initialization time so the platform controls its uniqueness
 * rather than discovering a collision after the fact. It is what every
 * subsequent webhook and reconciliation lookup keys on.
 *
 * <p>The {@link Version} column matters: a webhook delivery and a
 * reconciliation sweep can touch the same payment concurrently. Optimistic
 * locking makes the loser retry-or-fail rather than silently overwriting a
 * state transition the winner just made.
 */
@Entity
@Table(name = "payments",
        uniqueConstraints = @UniqueConstraint(name = "uk_payment_reference", columnNames = "reference"),
        indexes = {
                @Index(name = "idx_payment_status", columnList = "status"),
                @Index(name = "idx_payment_client", columnList = "client_id"),
                @Index(name = "idx_payment_worker", columnList = "skilled_worker_id")
        })
@Getter
@Setter
@NoArgsConstructor
public class Payment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "reference", nullable = false, updatable = false, length = 128)
    private String reference;

    @Enumerated(EnumType.STRING)
    @Column(name = "provider", nullable = false, updatable = false, length = 20)
    private PaymentProvider provider = PaymentProvider.PAYSTACK;

    /** Paystack's own numeric transaction id, learned from the first webhook or verify call. */
    @Column(name = "provider_transaction_id")
    private Long providerTransactionId;

    @Column(name = "client_id", nullable = false, updatable = false)
    private Long clientId;

    @Column(name = "skilled_worker_id", nullable = false, updatable = false)
    private Long skilledWorkerId;

    /** Optional link to the appointment being paid for. */
    @Column(name = "appointment_id", updatable = false)
    private Long appointmentId;

    @Column(name = "customer_email", nullable = false, updatable = false, length = 255)
    private String customerEmail;

    /** What the client was asked to pay, in minor units. */
    @Column(name = "amount_minor", nullable = false, updatable = false)
    private long amountMinor;

    /**
     * What the provider actually captured. Normally equal to
     * {@link #amountMinor}; a difference is a divergence the reconciliation
     * job reports rather than something the ledger papers over.
     */
    @Column(name = "captured_amount_minor", nullable = false)
    private long capturedAmountMinor;

    /** Running total refunded so far, across any number of partial refunds. */
    @Column(name = "refunded_amount_minor", nullable = false)
    private long refundedAmountMinor;

    /** The platform's commission on the captured amount; see {@code PaymentProperties}. */
    @Column(name = "platform_fee_minor", nullable = false)
    private long platformFeeMinor;

    /** Paystack's processing fee, as reported on the charge event. */
    @Column(name = "provider_fee_minor", nullable = false)
    private long providerFeeMinor;

    @Column(name = "currency", nullable = false, updatable = false, length = 3)
    private String currency;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 24)
    private PaymentStatus status = PaymentStatus.INITIATED;

    /** Paystack-hosted checkout URL handed back to the client at initialization. */
    @Column(name = "authorization_url", length = 512)
    private String authorizationUrl;

    @Column(name = "access_code", length = 128)
    private String accessCode;

    /** Provider-supplied reason for a {@code FAILED}/{@code ABANDONED} outcome. */
    @Column(name = "failure_reason", length = 500)
    private String failureReason;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt = Instant.now();

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt = Instant.now();

    /** When funds were captured — set once, on the transition into SUCCEEDED. */
    @Column(name = "captured_at")
    private Instant capturedAt;

    /** Last time a reconciliation sweep compared this payment against the provider. */
    @Column(name = "reconciled_at")
    private Instant reconciledAt;

    @Version
    private long version;

    public Payment(String reference, Long clientId, Long skilledWorkerId, Long appointmentId,
                   String customerEmail, long amountMinor, String currency) {
        this.reference = reference;
        this.clientId = clientId;
        this.skilledWorkerId = skilledWorkerId;
        this.appointmentId = appointmentId;
        this.customerEmail = customerEmail;
        this.amountMinor = amountMinor;
        this.currency = currency;
    }

    /** Amount captured that has not been refunded — what the books still hold for this payment. */
    public long netCapturedMinor() {
        return capturedAmountMinor - refundedAmountMinor;
    }
}
